---
title: "Code integration"
author: "Emmanuelle Comets"
date: "21/01/2021"
output:
  pdf_document: default
  html_document: default
---

### Objective

Set up a debugging framework:
- load libraries
- load package functions individually
- prepare objects for debugging functions

### Defining folders, loading libraries

```{r setup, include=FALSE,echo=FALSE,error=FALSE, warning=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
library(ggplot2)
library(gridExtra)
library(grid)
library(mclust)
library(testthat)
workDir<-"/home/eco/work/npde/npde30"
knitr::opts_chunk$set(root.dir = workDir)
notesDir<-file.path(workDir,"notebooks")
datDir<-file.path(workDir,"npde","data")
testsDir<-file.path(workDir,"npde","tests","testthat")
setwd(workDir)
```

### Creating NpdeObject using the current version of the package

```{r setupOldPackage, include=FALSE,echo=FALSE,error=FALSE, warning=FALSE,message=FALSE}
# Classes from the package
source(file.path(workDir,"npde","R","aaa_generics.R"))
source(file.path(workDir,"npde","R","npdeControl.R"))
source(file.path(workDir,"npde","R","NpdeData.R"))
source(file.path(workDir,"npde","R","NpdeSimData.R"))
source(file.path(workDir,"npde","R","NpdeData-methods.R"))
source(file.path(workDir,"npde","R","NpdeRes.R"))
source(file.path(workDir,"npde","R","NpdeRes-methods.R"))
source(file.path(workDir,"npde","R","NpdeObject.R"))
source(file.path(workDir,"npde","R","NpdeObject-methods.R"))

# Computational functions from the package
source(file.path(workDir,"npde","R","compute_distribution.R"))
source(file.path(workDir,"npde","R","compute_npde.R"))
source(file.path(workDir,"npde","R","compute_pd.R"))
source(file.path(workDir,"npde","R","compute_ploq.R"))
source(file.path(workDir,"npde","R","mainNpde.R"))
source(file.path(workDir,"npde","R","npde.R"))

# Plot functions from the package - kept, some changes
source(file.path(workDir,"npde","R","plotNpde-methods.R"))
source(file.path(workDir,"npde","R","plotNpde-plotFunctions.R"))
source(file.path(workDir,"npde","R","plotNpde-auxScatter.R")) 
source(file.path(workDir,"npde","R","plotNpde-auxScatterPlot.R")) 
source(file.path(workDir,"npde","R","plotNpde-auxDistPlot.R")) # renamed from plotNpde-unitFunctionsAux.R
source(file.path(workDir,"npde","R","plotNpde-distributionPlot.R")) # extracted "main" for distribution plots from plotNpde-plotFunctions.R
source(file.path(workDir,"npde","R","plotNpde-scatterplot.R")) # extracted "main" for scatter plots f
source(file.path(workDir,"npde","R","plotNpde-binningPI.R")) # renamed from plotNpde-unitFunctionsPI.R
```

### Run npde

- theophylline
- viral load (different)
- warfarin (2 models, covariates)

```{r runNpdeTheo, include=FALSE,echo=FALSE,error=FALSE, warning=FALSE,message=FALSE}

theofit1<-autonpde(file.path(datDir, "theopp.tab"),namsim=file.path(datDir, "simtheopp.tab"),1,3,4,boolsave=FALSE, units=list(x="hr",y="mg/L"))

# Warfarin data, using files on disk
wbase<-autonpde(namobs=file.path(datDir, "warfarin.tab"),namsim=file.path(datDir, "simwarfarinBase.tab"), iid=1,ix=2,iy=4,icov=c(3,6:8),namsav="warfBase", units=list(x="hr",y="ug/L", covariates=c("mg","kg","-","yr")))

wcov<-autonpde(namobs=file.path(datDir, "warfarin.tab"),namsim=file.path(datDir, "simwarfarinCov.tab"), iid=1,ix=2,iy=4,icov=c(3,6:8),namsav="warfBase", units=list(x="hr",y="ug/L", covariates=c("mg","kg","-","yr")))

# Warfarin with MDV
warfmdv<-read.table(file.path(datDir, "warfarin.tab"), header=TRUE)
idx<-sample(1:dim(warfmdv)[1], 10)
warfmdv$mdv<-0
warfmdv$mdv[idx]<-1
expect_equal(sum(warfmdv$mdv),10)

wmdv<-autonpde(namobs=warfmdv,namsim=file.path(datDir, "simwarfarinCov.tab"), iid=1,ix=2,iy=4,imdv=9,icov=c(3,6:8),namsav="warfBase", units=list(x="hr",y="ug/L", covariates=c("mg","kg","-","yr")))

```

```{r runNpdeVIH, include=FALSE,echo=FALSE,error=FALSE, warning=FALSE,message=FALSE}
virload<-read.table(file.path(datDir, "virload.tab"), header=TRUE)
virload20<-read.table(file.path(datDir, "virload20.tab"), header=TRUE)
virload50<-read.table(file.path(datDir, "virload50.tab"), header=TRUE)
simvirload<-read.table(file.path(datDir, "simvirload.tab"), header=TRUE)

yvir1<-autonpde(virload,simvirload,iid=1,ix=2,iy=3,boolsave=FALSE, units=list(x="hr", y="cp/mL, log 10 base"))

yvir20<-autonpde(virload20,simvirload,iid=1,ix=2,iy=3, icens=4, boolsave=FALSE)

yvir2<-autonpde(virload50,simvirload,iid=1,ix=2,iy=3,boolsave=FALSE)

yvir50<-autonpde(virload50,simvirload,iid=1,ix=2,iy=3, icens=4,boolsave=FALSE)

# Different methods to handle LOQ
yvir50.omit<-autonpde(virload50,simvirload,iid=1,ix=2,iy=3, icens=4,boolsave=FALSE, cens.method="omit")

yvir50.ppred<-autonpde(virload50,simvirload,iid=1,ix=2,iy=3, icens=4,boolsave=FALSE, cens.method="ppred")

yvir50.ipred<-autonpde(virload50,simvirload,iid=1,ix=2,iy=3, icens=4, iipred=5, boolsave=FALSE, cens.method="ipred")

```

### Debugging 

```{r debugSetup, echo=FALSE,error=FALSE, warning=FALSE,message=FALSE}
npde.plot.dist(yvir50.omit)
npde.plot.dist(yvir50.omit, dist.type="ecdf")
npdeObject<-yvir50.omit
which<-"npde"
plot.opt<-yvir50.omit@prefs

npde.plot.scatterplot(yvir50.omit)
npdeObject<-yvir50.omit
plot.opt<-yvir50.omit@prefs
which.x<-"x"
which.y<-which
ref.prof<-NULL

npde.plot.scatterplot(yvir50.omit)
plot(yvir50.omit, plot.type="x.scatter")

```
