---
title: "Testing library - current version 3.4"
author: "Emmanuelle Comets"
date: "15/06/2023"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Where to find the development files of npde (folders npde/R, keep, data)
workDir<-"/home/eco/work/npde/npde30/notebooks"
knitr::opts_chunk$set(root.dir = workDir)
setwd(workDir)
dir.create("testFiles")

library(npde)
```

# Theophylline

- computation of npde and npd
- default plots

```{r theo, echo=FALSE}
data(theopp)
data(simtheopp)

# Calling autonpde with dataframes
x<-autonpde(theopp,simtheopp,1,3,4,boolsave=FALSE)
plot(x)
head(x["results"]["res"])

plot(x, plot.type="hist")
```

- help file


```{r theohelp, echo=FALSE}
?autonpde

```

- saving graph

```{r theoSave, echo=FALSE}
x<-autonpde(theopp,simtheopp,1,3,4,boolsave=TRUE, type.graph="pdf")
cairo_pdf(filename="theoSave.pdf",height=8.27, width=11.69)
plot(x)
dev.off()
```
